### ISSUE TITLE
Open Tasks after migration

### ISSUE THREAD

**Issue by lblissett** [lblissett/dn-discuss#11]
- [x] Check if there are news migrated to events. The old site did not have news, so this needs to moved by hand. Its not important for outdated news, but you may know this better: @SinghJN @bits-of-static @jangermuller 
- [ ] Finish About page und Translation in German and English
- [x] Discuss workflow of new user registration

**Comment by jangermuller** [comment]
I agree with J

**Comment by jangermuller** [comment]
I agree. The problem with the old webpage was that one had to send around a conference CFP to send a simple announcement! It would be good to separate between news and events even though this is not always quite clear!

**Comment by lblissett** [comment]
The question was is there were news hidden in events in the old page which are important? We migrated events automatically from the old site. We cannot see if somebody used the event to post something which we would now consider as news. 

We have new members who want to use the site. Currently there are blocked, because the site-admins have to approve their registration. We can change this to a workflow without this approval step. How do you want to have this?

**Comment by SinghJN** [comment]
Intuitively I would say that we do not need the approval step, just to make exchanges easier and more user friendly. 

I don’t think it is very important if people post something as news that is actually an event or the other way around. The content of the message will make that clear.

**Comment by jangermuller** [comment]
I agree with Jaspal. We never had spammers. But if we have somebody in the future, we'll need to moderate the flow of messages.

**Comment by lblissett** [comment]
Yes, i opened up user registration without approval. New users have to validate their email address, though.
