### ISSUE TITLE
dnc3aled

### ISSUE THREAD

**Issue by bits-of-static** [lblissett/dn-discuss#13]
- [x] write howto for linking and image embedding  
- [x] give site-admins right to create new pages 
- [x] [main page](https://discourseanalysis.net/dnc3-aled-congress/)
  - [x] [english](https://discourseanalysis.net/dnc3-aled-congress/en)
    - [x] page structure
    - [x] interlink
    - [x] copy-paste content from old site
  - [ ] [french](https://discourseanalysis.net/dnc3-aled-congress/fr)
    - [ ] page structure
    - [ ] interlink
    - [ ] copy-paste content from old site
  - [ ] [spanish](https://discourseanalysis.net/dnc3-aled-congress/es)
    - [ ] page structure
    - [ ] interlink
    - [ ] copy-paste content from old site
  - [ ] [portugeese](https://discourseanalysis.net/dnc3-aled-congress/pt)
    - [ ] page structure
    - [ ] interlink
    - [ ] copy-paste content from old site
  - [ ] [german](https://discourseanalysis.net/dnc3-aled-congress/de)
    - [ ] page structure
    - [ ] interlink
    - [ ] copy-paste content from old site
  - [ ] [russian](https://discourseanalysis.net/dnc3-aled-congress/ru)
    - [ ] page structure
    - [ ] interlink
    - [ ] copy-paste content from old site
- [ ] remove the work links from the main page
- [ ] edit event to link to this dnc3aled page
- [ ] relink subdoman to point to here and not the event

**Comment by bits-of-static** [comment]
Creating a new page can be done from the tools page : https://discourseanalysis.net/siteadmin/tools

**Comment by bits-of-static** [comment]
The HTML editor has a bug we werenot able to fix. Workarounds can be found in the [wiki](https://github.com/lblissett/dn-discuss/wiki/Known-Bugs)

**Comment by bits-of-static** [comment]
I collected the links to the old page on the [main page](https://discourseanalysis.net/dnc3-aled-congress/).

**Comment by bits-of-static** [comment]
You have the rights to determine URL alias for each page.
The base is `/dnc3-aled-congress/`, the language variants `/dnc3-aled-congress/XX`. You can extend this pattern if you wish, but letting the system auto-generate a link is also fine in our opinion.

**Comment by bits-of-static** [comment]
All domains relinked.  For all but english, there pops us a "Construction Area Notice". Turned off for the rest of the site as well.

**Comment by jangermuller** [comment]
This now works great, thanks!!
