### ISSUE TITLE
Creation of new pages

### ISSUE THREAD

**Issue by jangermuller** [lblissett/dn-discuss#14]
I just created http://discourseanalysis.net/publications. Could you check whether the links can work? Could you link it with publications.discourseanalysis.net? Once it works, I would create the pages behind the links - but how?

**Comment by bits-of-static** [comment]
Please create the pages before and I will link it afterwards. Pages with broken links are ranked down by search engines.

I wrote a wiki on creating interlinked page areas: https://github.com/lblissett/dn-discuss/wiki/Creating-Complex-Pages

**Comment by jangermuller** [comment]
Yes, we've created interlinked pages now!

**Comment by bits-of-static** [comment]
ok, closing this issue.
