### ISSUE TITLE
Amazon SES

### ISSUE THREAD

**Issue by bits-of-static** [lblissett/dn-discuss#17]
Hallo Johannes,

wir wollten den Amazon SES für emailing einbinden. Das ist zwar umsonst - setzt allerdings ein Amazon EC2 Service voraus.

Die Kosten-Erwartungen sind unter 10 euro im Jahr. Man muss allerdings eine Kreditkarte vorausstrecken und ich selber habe keine. Ich habe eine Anfrage an Support herausgeschickt, ob man Bezahlung und technische Administration trennen kann - sollte, muss aber nicht möglich sein. Ich melde mir diesbezüglich noch.

Lass mich bitte wissen ob sich das machen lässt oder ob wir ein anderes Dienst suchen müssen.

**Comment by jangermuller** [comment]
OK, aber Paypal waere noch besser!

**Comment by bits-of-static** [comment]
Könnten wir heute hierzu telefonieren und du würdest mir die Angaben durchsagen damit ich den account aufmachen kann? 

Ich werde brauchen:  
Credit/Debit card number
Expiration date
Cardholder's name
Billing address (Full name, Phone number, Address: Street, City, Postal code)

**Comment by bits-of-static** [comment]
Martin hat mich hingewiesen, dass die Kosten doch höher liegen könnten, da es sich uU. nicht um "on demand" computation platform handelt, sondern es wird für Verfügbarkeit bezahlt. In dem fall wären die kosten bei 50 Euro im Jahr (4.50 monatlich)

**Comment by jangermuller** [comment]
Ich denke, wir haben keine grosse Wahl und es muss eine schnelle, sichere und dauerhafte Loesung geben!

**Comment by bits-of-static** [comment]
Ja. Ruf mich bitte an wegen den payment angaben. Es steht zwar, dass auch debit karten akzeptiert werden, aber es muss eine bank karte sein, deren nummer duch deren validator durchpasst. Und ich habe keine solche.

**Comment by bits-of-static** [comment]
Ich wurde grade eben von Amazon angerufen und folgendes haben die mir vorgeschlagen: Du kannst ein account aufmachen und mir dadrunter rechte für bestimmte produkte geben.

https://portal.aws.amazon.com/gp/aws/developer/registration/index.html

Wir brauchen ein `EC2 T3.nano` und dann den bereits erwähntes `SES` dienst. Erster jahr ist umsonst. Danach 0.006euro pro stunde. https://aws.amazon.com/ec2/pricing/on-demand/

Wenn dir das zu viel Aufwand ist zu administrieren, dann eben der anderer weg, dass du mich die karten nummern wissen lässt.

**Comment by jangermuller** [comment]
Das ist super. Soll ich dir meine Amazon Daten geben?

**Comment by bits-of-static** [comment]
Hast dir ein Amazon AWS Account erstellt? Nein, das solltest du da alles selber verwalten.

Mich hinzufügen als jemanden der bestimmte Bereiche von deinem Account nutzen kann. Bitte die Einladung auf `amazon.com_discourseanalysis.net@informatik-handwerk.de` zuschicken.

**Comment by jangermuller** [comment]
Hab mich angemeldet. Wo kann ich dich einladen? Schaut komplex aus!

**Comment by jangermuller** [comment]
Das nennt sich basic und ist free?

**Comment by jangermuller** [comment]
Geht die verschickubg jetzt?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
