### ISSUE TITLE
link publications

### ISSUE THREAD

**Issue by jangermuller** [lblissett/dn-discuss#18]
Within https://discourseanalysis.net/publications I can't make links. Could there be a small editable area where there could be a link to https://discourseanalysis.net/DN/publications ?

**Comment by bits-of-static** [comment]
/publications war ein system link, der zu der durchsuchbaren liste von Publikationen führte die wir importierten.

Gib uns bitte neuen Link unter den wir die Datenbank Inhalte ausgeben oder versuche ein anderes URL zu finden. Generell - wenn man eigene URL vergeben möchte - immer kontrollieren ob die nicht belegt ist. Wir werden das nicht kontrollieren (können).

**Comment by jangermuller** [comment]
Existierende Seiten wuerden einfach ueberschrieben - oh wei!! Ich koennte schon drei neue machen, aber die existierenden drei Seiten sind eigentlich super. Man muesste oben nur jeweils ein bisschen erklaeren... Was meinst du?

**Comment by bits-of-static** [comment]
Du musst dann keine neuen machen und alte löschen - es reicht auch die zu editiere und die URLs korrigieren.

Ja `/publications` zeigt jetzt datenbank inhalte wieder, danke.
