### ISSUE TITLE
Groups list of members

### ISSUE THREAD

**Issue by jangermuller** [lblissett/dn-discuss#19]
In a group like this, people don't usually have images. https://discourseanalysis.net/group/16 Could you list the names and institutions only without image?

**Comment by bits-of-static** [comment]
All groups use the same template - do you want to remove the avatar for all groups?

**Comment by jangermuller** [comment]
Yes, I would suggest just displaying name and institution!

**Comment by bits-of-static** [comment]
Implemented in 5aed390b, closing
