### ISSUE TITLE
DN events Anzeige

### ISSUE THREAD

**Issue by jangermuller** [lblissett/dn-discuss#20]
Auf der Landing Page sieht man noch das GGS event, das vor einer Woche zu Ende ging. Wird das nach dem Ende nicht automatisch rausgenommen und wo kann man die DN events ggf. editieren?  Es muesste hier zu allererst DNC3-ALED Paris auftauchen: https://discourseanalysis.net/en/third-discoursenet-aled-congress-dnc3-aled-knowledge-and-power-polycentric-world-discourses

**Comment by jangermuller** [comment]
DNC3ALED muesste in der Liste als erstes erscheinen !

**Comment by jangermuller** [comment]
Ich schreib mal, was heute sehr dringend ist: 

1) DNC3ALED am Anfang auf den Events der Landing Page und 

2) die vier Fake Subdomains der Konferenz, die immer noch nicht gehen, naemlich 
 http://dnc3aled.diskursanalyse.net | https://discourseanalysis.net/DNC3ALED/DE
  http://dnc3aled.analysedudiscours.net | https://discourseanalysis.net/DNC3ALED/FR
  http://dnc3aled.analisisdeldiscurso.net | https://discourseanalysis.net/DNC3ALED/ES
  http://dnc3aled.analisedodiscurso.net | https://discourseanalysis.net/DNC3ALED/PT 

3) Die naechste Prioritaet danach waere die Moeglichkeit, Nachrichten zu versenden.

**Comment by lblissett** [comment]
I implemented a new logic for the dn-events on the frontpage:

- events in the past will not be shown (they will be shown for another five days after they were finished and then disappear from the frontpage)
- dn events will be shown for the next 365 days (up to 3 events)

DNC3ALED is now shown on the frontpage. But it is not the first in the list. At least not at the moment, once the other events are finished it will be first in the list. 

This is an autonmous workflow. We can easily change the numbers e.g. show four dn-events. or make events dissapear on the same day they were finished.

It is also possible to give you more control. If you really want this to be different we can change this and give you the opportunity to micromanage the order of the shown events at the cost that with greater power comes greater responsibility / communication overhead.

**Comment by jangermuller** [comment]
Great - looks perfect!
